#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Waybar
Version  : 0.8.0
Release  : 1
URL      : https://github.com/Alexays/Waybar/archive/0.8.0.tar.gz
Source0  : https://github.com/Alexays/Waybar/archive/0.8.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: Waybar-bin = %{version}-%{release}
Requires: Waybar-man = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : pkgconfig(dbusmenu-gtk3-0.4)
BuildRequires : pkgconfig(fmt)
BuildRequires : pkgconfig(gtkmm-3.0)
BuildRequires : pkgconfig(jsoncpp)
BuildRequires : pkgconfig(libinput)
BuildRequires : pkgconfig(libmpdclient)
BuildRequires : pkgconfig(libnl-3.0)
BuildRequires : pkgconfig(libnl-genl-3.0)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(scdoc)
BuildRequires : pkgconfig(spdlog)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(wayland-protocols)

%description
# Waybar [![Travis](https://travis-ci.org/Alexays/Waybar.svg?branch=master)](https://travis-ci.org/Alexays/Waybar) [![Licence](https://img.shields.io/badge/License-MIT-yellow.svg)](LICENSE) [![Paypal Donate](https://img.shields.io/badge/Donate-Paypal-2244dd.svg)](https://paypal.me/ARouillard)<br>![Waybar](https://raw.githubusercontent.com/alexays/waybar/master/preview-2.png)

%package bin
Summary: bin components for the Waybar package.
Group: Binaries

%description bin
bin components for the Waybar package.


%package man
Summary: man components for the Waybar package.
Group: Default

%description man
man components for the Waybar package.


%prep
%setup -q -n Waybar-0.8.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571170177
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/waybar

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/waybar-backlight.5
/usr/share/man/man5/waybar-battery.5
/usr/share/man/man5/waybar-clock.5
/usr/share/man/man5/waybar-cpu.5
/usr/share/man/man5/waybar-custom.5
/usr/share/man/man5/waybar-idle-inhibitor.5
/usr/share/man/man5/waybar-memory.5
/usr/share/man/man5/waybar-mpd.5
/usr/share/man/man5/waybar-network.5
/usr/share/man/man5/waybar-pulseaudio.5
/usr/share/man/man5/waybar-states.5
/usr/share/man/man5/waybar-sway-mode.5
/usr/share/man/man5/waybar-sway-window.5
/usr/share/man/man5/waybar-sway-workspaces.5
/usr/share/man/man5/waybar-temperature.5
/usr/share/man/man5/waybar-tray.5
/usr/share/man/man5/waybar.5
